//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class getAllKategori
    {
        public byte ID { get; set; }
        public string AD { get; set; }
        public Nullable<int> kitapSayisi { get; set; }
    }
}
