//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHareket
    {
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<byte> PERSONEL { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public string ISLEMTURU { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
    
        public virtual tblKitap tblKitap { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        public virtual tblUyeler tblUyeler { get; set; }
    }
}
